### ISSUE TITLE
Flamethrowers can't be reloaded

### ISSUE THREAD

**Issue by CocaColaTastesGood** [fortune13-ss13/thewasteland#650]
## Reproduction:
Shoot a flamethrower. When empty the flamethrower cannot be reloaded.

**Comment by BadAtThisGame302** [comment]
The NCR flamethrower is reloaded by napalm.

**Comment by CocaColaTastesGood** [comment]
You're right, to be more specific it's reloaded by flamethrower fuel crafted with napalm.
